# Generated by Django 5.2.9 on 2025-12-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_code',
            field=models.CharField(default='#ffffff', max_length=70, verbose_name='Код цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_name',
            field=models.CharField(default='Белый', max_length=70, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
