# Generated by Django 5.2.9 on 2025-12-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_alter_product_color_code_alter_product_color_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_code',
            field=models.CharField(default='#ffffff', max_length=70, verbose_name='Код света'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_name',
            field=models.CharField(default='Белый', max_length=70, verbose_name='Название света'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(verbose_name='описание'),
        ),
    ]
