# Generated by Django 5.2.9 on 2025-12-12 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0006_characteristic_characteristicvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, verbose_name='Значение')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital.characteristic', verbose_name='Тип характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_characteristics', to='digital.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товара',
            },
        ),
        migrations.DeleteModel(
            name='CharacteristicValue',
        ),
        migrations.AddConstraint(
            model_name='productcharacteristic',
            constraint=models.UniqueConstraint(fields=('product', 'characteristic'), name='unique_characteristic_per_product'),
        ),
    ]
