# Generated by Django 5.2.9 on 2025-12-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0007_productcharacteristic_delete_characteristicvalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
