# Generated by Django 5.2.9 on 2025-12-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0008_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото товара'),
        ),
        migrations.DeleteModel(
            name='ImagesProduct',
        ),
    ]
