# Generated by Django 5.2.9 on 2025-12-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0009_product_image_delete_imagesproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=10, verbose_name='Количество товара'),
        ),
    ]
