# Generated by Django 5.2.9 on 2025-12-20 11:43

import digital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0012_remove_profile_phone_number_alter_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=digital.models.user_photo_path, verbose_name='Фото профеля'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
