# Generated by Django 5.2.9 on 2026-01-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0017_city_region_delivery_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
