# Generated by Django 5.2.9 on 2026-01-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0018_delivery_email_delivery_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='city',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='region',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
