# Generated by Django 5.2.9 on 2026-01-06 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0019_remove_delivery_city_remove_delivery_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер получателя')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления доставки')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('address', models.CharField(max_length=100, verbose_name='Адресс')),
                ('status', models.BooleanField(default=False, verbose_name='Статус доставки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Доставку',
                'verbose_name_plural': 'Доставки',
            },
        ),
    ]
