# Generated by Django 5.2.9 on 2026-01-08 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0020_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Цена заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оплаты заказа')),
                ('completed', models.BooleanField(default=0, verbose_name='Статус оплаты заказа')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital.cart', verbose_name='Корзина')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital.customer', verbose_name='Покупатель')),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='digital.delivery', verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы покупателей',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название товара')),
                ('slug', models.CharField(max_length=300, verbose_name='Слаг товара')),
                ('price', models.IntegerField(default=0, verbose_name='Цена товара')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Фото товара')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('total_price', models.IntegerField(default=0, verbose_name='На сумму в кол-во')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказов',
            },
        ),
    ]
