# Generated by Django 5.2.9 on 2026-01-11 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0023_productorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='digital.product', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
