# Generated by Django 5.2.9 on 2026-01-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0024_alter_productorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
    ]
