# Generated by Django 5.2.9 on 2026-01-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0025_remove_productorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='color_name',
            field=models.CharField(default='Белый', max_length=70, verbose_name='Название света'),
        ),
    ]
